config/routes.rb
Rails.application.routes.draw do
  post '/adicionar', to: 'celulas#add_to_celula', as: :add_to_cell
  root 'metas_gerais#index'
  put '/troca', to: 'tasks#change_status', as: :task_change_status
  resources :projects
  resources :technologies
  resources :tags
  resources :articles
  mount Ckeditor::Engine => '/ckeditor'
  resources :tasks
  resources :goals
  resources :celulas
  resources :posts
  devise_for :users, :controllers => {registrations: 'registration'}, skip: [:sessions]
  as :user do
    get '/login', to: 'devise/sessions#new', as: :new_user_session
    post '/login', to: 'devise/sessions#create', as: :user_session
    delete '/logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  resources :users
  resources :offices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do 
    member do 
      put 'like' => "posts#like"
      put 'dislike' => "posts#dislike"
    end
  end 
end

app/models/article.rb
class Article < ApplicationRecord
    has_and_belongs_to_many :tags
end

app/models/celula.rb
class Celula < ApplicationRecord
  belongs_to :user
end

app/models/fusion.rb
class Fusion < ApplicationRecord
  belongs_to :user
  belongs_to :office
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :celula, optional: true
  belongs_to :office, optional: true
end

app/models/office.rb
class Office < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  acts_as_votable
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :technology
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :articles
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :goal
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/technology.rb
class Technology < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validate :email_domain
  
  mount_uploader :image, ImageUploader

  def email_domain
    domain = email.split("@").last
    if !email.blank?
      errors.add(:email, "Domínio Inválido") if domain != "injunior.com.br"
    end
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]
  before_action :soAdm, only: [:new]
  before_action :AdmDir, only: [:edit]

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Diretoria criada.' }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: 'Diretoria atualizada.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:name, :user_id)
    end

    def soAdm
      if !current_user.admin
        redirect_to offices_path
      end
    end

    def AdmDir
      if (!current_user.admin) || (!Office.find_by(user_id: current_user.id))
        redirect_to offices_path
      end
    end 

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/celulas_helper.rb
module CelulasHelper
end

app/helpers/fusions_helper.rb
module FusionsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/offices/_form.html.erb
<%= form_with(model: office, local: true) do |form| %>
  <% if office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% office.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: "Nome", class: "input-gerador" %>
  </div>

  <div class="conteudo-gerador">
    <%= form.label :diretor %>
    <%= form.collection_select(:user_id, User.all, :id, :email) %>

    <%= form.submit %>
  </div>
<% end %>

app/views/offices/edit.html.erb
<div class="cartao-gerador">

    <h1>Editando Diretoria</h1>

    <%= render 'form', office: @office %>
    <div class=""botoes-artigo>
    <%= link_to 'Back', offices_path, class: "btn btn-secondary" %>
    </div>
</div>

app/views/offices/index.html.erb
<body>
  

  <section id="apresentacao">
    <div class="container-apresentacao">
      <h1>Diretorias</h1>
      <% if current_user.admin %>
        <%= link_to 'New Office', new_office_path, class: "button-universal" %>
      <% end %>
    </div>
  </section>

  <div class="container-new">
    <hr>
  </div>

  <section id="conteudo">
    <div class="container-metas">
      
      <% @offices.each do |office| %>

        <div class="cartao-celulas">

          <div class="container-titulo">
            <%= link_to office.name, office, class: "nome-celulas" %>
            <hr>
          </div>

          <div class="conteudo">
            
            <div class="simbolo">
              <%= image_tag("comercial.jpeg", alt: "simbolo células", class: "imagem-celula") %>
            </div>

            <div class="gerente">
              <h2>Diretor:</h2>
              <h3>James Solzinho</h3>
              <h3><%= office.user.name %></h3>
            </div>
            
          </div>

          <div class="botoes-artigo">
            <% if (current_user.office_id) %>
              <% if (current_user.office_id == @office.id) || current_user.admin %>
                <%= link_to 'Editar', edit_office_path(office), class: "button-universal" %>
              <% end %>
            <% end %>
            <% if current_user.admin %>
              <%= link_to 'Deletar', office, method: :delete, data: { confirm: 'Tem certeza?' }, class: "button-universal" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </section>
  

app/views/offices/new.html.erb
<div class="cartao-gerador">
    <h1>New Office</h1>

    <%= render 'form', office: @office %>

    <div class=""botoes-artigo>
        <%= link_to 'Back', offices_path, class: "btn btn-secondary" %>
    </div>
</div>

app/views/offices/show.html.erb
<body>
  
<div class="cartao-container">

    <div class="container-show">
      <h1>Diretoria de</h1>
      <h1><%= @office.name %></h1>
    </div>

    <div class="conteudo-show">
      <p>
        <strong>Diretor:</strong>
        <%= @office.user.name %>
      </p>

      <p>
        <strong>Assessores:</strong>
      </p>
    </div>

      <% assessores = User.where(office_id: @office.id) %>
      <% assessores.each do |assessor| %>
        <% if assessor.id == @office.user_id %>
          <% assessores.delete(assessor)%>
        <% end %>
      <% end %>
      <% assessores.each do |assessor| %>
        <p>
          <%= assessor.name %>
        </p>
      <% end %>
      <div class="botoes-artigo">
        <% if current_user.admin || (@office.user_id==current_user.id) %>
          <%= link_to 'Editar', edit_office_path(@office), class: "button-universal" %> 
        <% end %>
        <%= link_to 'Metas', goals_path, class: "button-universal" %>
        <%= link_to 'Voltar', offices_path, class: "button-universal" %>
      </div>
  </div>

</body>