config/routes.rb
Rails.application.routes.draw do
  post '/adicionar', to: 'celulas#add_to_celula', as: :add_to_cell
  root 'metas_gerais#index'
  put '/troca', to: 'tasks#change_status', as: :task_change_status
  resources :projects
  resources :technologies
  resources :tags
  resources :articles
  mount Ckeditor::Engine => '/ckeditor'
  resources :tasks
  resources :goals
  resources :celulas
  resources :posts
  devise_for :users, :controllers => {registrations: 'registration'}, skip: [:sessions]
  as :user do
    get '/login', to: 'devise/sessions#new', as: :new_user_session
    post '/login', to: 'devise/sessions#create', as: :user_session
    delete '/logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  resources :users
  resources :offices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do 
    member do 
      put 'like' => "posts#like"
      put 'dislike' => "posts#dislike"
    end
  end 
end

app/models/article.rb
class Article < ApplicationRecord
    has_and_belongs_to_many :tags
end

app/models/celula.rb
class Celula < ApplicationRecord
  belongs_to :user
end

app/models/fusion.rb
class Fusion < ApplicationRecord
  belongs_to :user
  belongs_to :office
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :celula, optional: true
  belongs_to :office, optional: true
end

app/models/office.rb
class Office < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  acts_as_votable
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :technology
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :articles
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :goal
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/technology.rb
class Technology < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validate :email_domain
  
  mount_uploader :image, ImageUploader

  def email_domain
    domain = email.split("@").last
    if !email.blank?
      errors.add(:email, "Domínio Inválido") if domain != "injunior.com.br"
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:identification, :name)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/celulas_helper.rb
module CelulasHelper
end

app/helpers/fusions_helper.rb
module FusionsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :identification %>
    <%= form.number_field :identification %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Identification</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.identification %></td>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identification:</strong>
  <%= @tag.identification %>
</p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>