config/routes.rb
Rails.application.routes.draw do
  post '/adicionar', to: 'celulas#add_to_celula', as: :add_to_cell
  root 'metas_gerais#index'
  put '/troca', to: 'tasks#change_status', as: :task_change_status
  resources :projects
  resources :technologies
  resources :tags
  resources :articles
  mount Ckeditor::Engine => '/ckeditor'
  resources :tasks
  resources :goals
  resources :celulas
  resources :posts
  devise_for :users, :controllers => {registrations: 'registration'}, skip: [:sessions]
  as :user do
    get '/login', to: 'devise/sessions#new', as: :new_user_session
    post '/login', to: 'devise/sessions#create', as: :user_session
    delete '/logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  resources :users
  resources :offices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do 
    member do 
      put 'like' => "posts#like"
      put 'dislike' => "posts#dislike"
    end
  end 
end

app/models/article.rb
class Article < ApplicationRecord
    has_and_belongs_to_many :tags
end

app/models/celula.rb
class Celula < ApplicationRecord
  belongs_to :user
end

app/models/fusion.rb
class Fusion < ApplicationRecord
  belongs_to :user
  belongs_to :office
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :celula, optional: true
  belongs_to :office, optional: true
end

app/models/office.rb
class Office < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  acts_as_votable
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :technology
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :articles
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :goal
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/technology.rb
class Technology < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validate :email_domain
  
  mount_uploader :image, ImageUploader

  def email_domain
    domain = email.split("@").last
    if !email.blank?
      errors.add(:email, "Domínio Inválido") if domain != "injunior.com.br"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :dislike]

  # GET /posts
  # GET /posts.json
  def index
    @posts = if params[:term]
      Post.where('title LIKE ?', "%#{params[:term]}%")
    else
      Post.all
    end
  end
  

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def like
    @post.like_by current_user
    redirect_to posts_path
  end

  def dislike
    @post.disliked_by current_user
    redirect_to posts_path
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :term)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/celulas_helper.rb
module CelulasHelper
end

app/helpers/fusions_helper.rb
module FusionsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Forúm dos Lobos</h1>
  <p class="lead">Pergunte aos lobos e eles lhe darão um caminho.</p>
  <hr class="my-4">  
</div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<%= form_tag(posts_path, method: :get) do %>
  <%= text_field_tag :term, params[:term], placeholder: 'Procurar um artigo...' %>
  <%= submit_tag 'Buscar' %>
<% end %>



  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user.email %></td>
        <td><%= link_to like_post_path(post), class: "like", method: :put do%>
          <button type="button" class="btn btn-default btn-sm">
              <span class="glyphicon glyphicon-thumbs-up"> <%=post.get_likes.size%></span> Likes
          </button>
        <%end%></td>
        
        <td><%= link_to dislike_post_path(post), class: "like", method: :put do%>
          <button type="button" class="btn btn-default btn-sm">
             <span class="glyphicon glyphicon-thumbs-down"> <%=post.get_dislikes.size%></span> Dislikes
          </button>
        <%end%></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>