config/routes.rb
Rails.application.routes.draw do
  post '/adicionar', to: 'celulas#add_to_celula', as: :add_to_cell
  root 'metas_gerais#index'
  put '/troca', to: 'tasks#change_status', as: :task_change_status
  resources :projects
  resources :technologies
  resources :tags
  resources :articles
  mount Ckeditor::Engine => '/ckeditor'
  resources :tasks
  resources :goals
  resources :celulas
  resources :posts
  devise_for :users, :controllers => {registrations: 'registration'}, skip: [:sessions]
  as :user do
    get '/login', to: 'devise/sessions#new', as: :new_user_session
    post '/login', to: 'devise/sessions#create', as: :user_session
    delete '/logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  resources :users
  resources :offices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do 
    member do 
      put 'like' => "posts#like"
      put 'dislike' => "posts#dislike"
    end
  end 
end

app/models/article.rb
class Article < ApplicationRecord
    has_and_belongs_to_many :tags
end

app/models/celula.rb
class Celula < ApplicationRecord
  belongs_to :user
end

app/models/fusion.rb
class Fusion < ApplicationRecord
  belongs_to :user
  belongs_to :office
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :celula, optional: true
  belongs_to :office, optional: true
end

app/models/office.rb
class Office < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  acts_as_votable
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :technology
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :articles
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :goal
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/technology.rb
class Technology < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validate :email_domain
  
  mount_uploader :image, ImageUploader

  def email_domain
    domain = email.split("@").last
    if !email.blank?
      errors.add(:email, "Domínio Inválido") if domain != "injunior.com.br"
    end
  end
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :set_technology, only: [:show, :edit, :update, :destroy]

  # GET /technologies
  # GET /technologies.json
  def index
    @technologies = Technology.all
  end

  # GET /technologies/1
  # GET /technologies/1.json
  def show
  end

  # GET /technologies/new
  def new
    @technology = Technology.new
  end

  # GET /technologies/1/edit
  def edit
  end

  # POST /technologies
  # POST /technologies.json
  def create
    @technology = Technology.new(technology_params)

    respond_to do |format|
      if @technology.save
        format.html { redirect_to @technology, notice: 'Technology was successfully created.' }
        format.json { render :show, status: :created, location: @technology }
      else
        format.html { render :new }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technologies/1
  # PATCH/PUT /technologies/1.json
  def update
    respond_to do |format|
      if @technology.update(technology_params)
        format.html { redirect_to @technology, notice: 'Technology was successfully updated.' }
        format.json { render :show, status: :ok, location: @technology }
      else
        format.html { render :edit }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technologies/1
  # DELETE /technologies/1.json
  def destroy
    @technology.destroy
    respond_to do |format|
      format.html { redirect_to technologies_url, notice: 'Technology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technology
      @technology = Technology.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technology_params
      params.require(:technology).permit(:name)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/celulas_helper.rb
module CelulasHelper
end

app/helpers/fusions_helper.rb
module FusionsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/technologies/_form.html.erb
<%= form_with(model: technology, local: true) do |form| %>
  <% if technology.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(technology.errors.count, "error") %> prohibited this technology from being saved:</h2>

      <ul>
      <% technology.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/technologies/edit.html.erb
<h1>Editing Technology</h1>

<%= render 'form', technology: @technology %>

<%= link_to 'Show', @technology %> |
<%= link_to 'Back', technologies_path %>

app/views/technologies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Technologies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @technologies.each do |technology| %>
      <tr>
        <td><%= technology.name %></td>
        <td><%= link_to 'Show', technology %></td>
        <td><%= link_to 'Edit', edit_technology_path(technology) %></td>
        <td><%= link_to 'Destroy', technology, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Technology', new_technology_path %>

app/views/technologies/new.html.erb
<h1>New Technology</h1>

<%= render 'form', technology: @technology %>

<%= link_to 'Back', technologies_path %>

app/views/technologies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @technology.name %>
</p>

<%= link_to 'Edit', edit_technology_path(@technology) %> |
<%= link_to 'Back', technologies_path %>